---
- hosts: backup
  user: ubuntu
  become: yes
  become_method: sudo
  vars_files:
    - "vars.yml"
  roles:
  - { role: setup, tags: setup_backup}
  - { role: backup_push, tags: setup_backup}
  - { role: restore_database, tags: restore_db}