---
- name: get path for automysqlbackup
  command: bash -c "which automysqlbackup"
  register: automysqlbackup_path
  tags:
    - crontab

- name: get path for aws
  command: bash -c "which aws"
  register: aws_path
  tags:
    - crontab

- name: Copy cron tab file to /etc/cron.d directory
  template: src=sqlbackup dest=/etc/cron.d
  tags:
    - crontab