---
- name: get path for automysqlbackup
  command: bash -c "which automysqlbackup"
  register: automysqlbackup_path
  tags:
    - copy_backup_script

- name: get path for aws
  command: bash -c "which aws"
  register: aws_path
  tags:
    - copy_backup_script

- name: check if mysqlworkbench exists
  command: bash -c "dpkg --get-selections | grep 'mysql-workbench'"
  register: mysqlworkbench_exists
  tags:
    - mysql_workbench

- name: Install mysqlworkbench
  when: mysqlworkbench_exists|failed
  apt: name=mysql-workbench state=present
  tags:
    - mysql_workbench

- name: check if system backup file exists
  command: bash -c "ls {{ansible_env.PWD}} | grep sysbackup"
  register: file_exists
  ignore_errors: true
  tags:
    - backup_file

- name: create backup file
  file: path={{ansible_env.PWD}}/sysbackup state=directory
  when: file_exists|failed
  tags:
    - backup_file

- name: Copy cron tab file to /etc/cron.d directory
  template: src=backup dest=/etc/cron.d
  tags:
    - copy_cron_file

- name: Copy backup script to /home/ubuntu directory
  template: src=backup.sh dest={{ansible_env.PWD}} mode=0774
  tags:
    - copy_backup_script