---
- name: check if backup directory exists
  command: bash -c "ls {{ansible_env.PWD}} | grep {{ backup_dir }}"
  register: dir_exists
  ignore_errors: true
  tags:
    - crontab

- name: create backup directory
  file: path={{ansible_env.PWD}}/{{ backup_dir }} state=directory mode=0755
  when: dir_exists|failed
  tags:
    - crontab

- name: Copy cron tab file to /etc/cron.d directory
  template: src=sqlbackup dest=/etc/cron.d
  tags:
    - crontab