---
- name: check if restore directory exists
  command: bash -c "ls {{ansible_env.PWD}} | grep restore"
  register: dir_exists
  ignore_errors: true
  tags:
    - restore_dir

- name: create restore directory
  file: path={{ansible_env.PWD}}/restore state=directory
  when: dir_exists|failed
  tags:
    - restore_dir

- name: Copy cron tab file to /etc/cron.d directory
  template: src=confirm_backup dest=/etc/cron.d
  tags:
    - copy_restore_file

- name: Copy restore script to /home/ubuntu directory
  template: src=confirm_backups.sh dest={{ansible_env.PWD}} mode=0774
  tags:
    - copy_confirm_script

- name: check for difference in files
  command: bash -c "cat {{ansible_env.PWD}}/tmp.txt"
  tags:
    - confirm_backup
